server:
  port: 8001
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: vlzk@@8462
    key-store-type: PKCS12

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aucation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #url: jdbc:mysql://k9b104.p.ssafy.io:3306/aucation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  mail:
    username: wodnr8462@naver.com
    password: vlzk@@8462

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false

jwt:
  secretKey: myssafyislikeherewowwowwow123123123
  accessToken:
    expiration: 8640000
  refreshToken:
    expiration: 126000000
  tokenAuthorizationWhiteList: /api/v1/members/login, /api/v1/members/verification/

