server:
  port: 9001
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: vlzk@@8462
#    key-store-type: PKCS12

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://localhost:3306/aucation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://k9b104.p.ssafy.io:3306/aucation?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: q1w2e3r4!

  # spring data jpa ??
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
  freemarker:
    cache: false
  jackson:
    serialization:
      fail-on-empty-beans: false

  redis:
    # redis cluster설정
    cluster:
      nodes:
#        - 3.34.50.200:6379 # 기본지급 master 1
#        - 3.34.50.200:6378 # 기본지급 slave 1
#        - 3.34.50.200:6479 # 기본지급 master 2
#        - 3.34.50.200:6478 # 기본지급 slave 2
#        - 3.36.93.23:6379  # 추가지급 master1
#        - 3.36.93.23:6378  # 추가지급 slave 1
        3.34.50.200:6379,
        3.34.50.200:6378,
        3.34.50.200:6479,
        3.34.50.200:6478,
        3.36.93.23:6379,
        3.36.93.23:6378
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2


jwt:
  secretKey: myssafyislikeherewowwowwow123123123
  accessToken:
    expiration: 8640000
  refreshToken:
    expiration: 126000000
  tokenAuthorizationWhiteList: /api/v1/members/login, /api/v1/members/verification/ , /api/v1/members/certification