pipeline {
    agent any
    stages {
               
    stage('Build Docker-Compose') {
                    steps {
	           sh 'docker compose -f /var/jenkins_home/workspace/aucation-back/docker-compose.yml build server'
                    }
                }

  stage('Docker stop'){
            steps {
                dir('BE'){
                    sh 'echo "Docker Container Stop"'
                    sh 'docker compose stop auc-back'
                }
 
            }
            post {
                 failure {
                     sh 'echo "Docker Fail"'
                }
            }
        }


 	stage('Up Docker-Compose') {
                    steps {
	           sh 'docker compose -f /var/jenkins_home/workspace/aucation-back/docker-compose.yml up -d server'
                    }
                }

    
     stage('RM Docker'){
            steps {
                
                sh 'echo "Remove Docker"'
 
                // 안쓰는이미지 -> <none> 태그 이미지 찾아서 삭제함
                sh '''
                    result=$(docker images -f "dangling=true" -q)
                    if [ -n "$result" ]
                    then
                        docker rmi -f $(docker images -f "dangling=true" -q)
                    else
                        echo "No such container images"
                    fi
                '''
 
            }
            post {
                 failure {
                     sh 'echo "Remove Fail"'
                }
            }
        }
    }
}
