pipeline {
    agent any


    stages {
               
        stage('Build Docker-Compose') {
                    steps {
	           sh 'docker compose -f /var/test123/docker-compose.yml build'
                    }
                }
 	stage('Up Docker-Compose') {
                    steps {
	           sh 'docker compose -f /var/jenkins_home/workspace/aucation-back/docker-compose.yml up -d'
                    }
                }
    }
}
